### PR TITLE
Show matched elements with children but remove the unmatched

### PR DESCRIPTION
**Pull request by golikov**
There might be a quite common use case when a person would like to see the children of nodes, matched by search, yet have the behavior of show_only_matches in all other respects. It could be a good idea to introduce changes as follows.

### CODE REVIEW

**Comment by vakata** [comment]
Thank you for the contribution, I believe something similar is already available here as a separate plugin, that you can copy and include: https://github.com/vakata/jstree/blob/master/src/misc.js#L127

I might consider adding your solution to the core, as it is such a small change, but unfortunately you need to also deal with the `jstree-last` class - from what I see you are not reseting it, which will cause a visual "bug" if you have a for example: a matching node, that has 2 children, and the first child is also a match.

Best regards,
Ivan

**Comment by golikov** [comment]
Hi Ivan,
Thank you for your feedback. I do not mean to argue but I tested the case you mentioned and found no visual bug.
It's true that i don't set jstree-last class. Your code does it very nicely for me.
First you remove jstree-last class from everything that has a sibling.
Then i make the children visible with my line of code.
Then your code attaches jstree-last to the last visible child (mine are already visible by this time).
I just added a line to a comfy place. Please, explain if I'm wrong here.

Best regards,
Nick

**Comment by vakata** [comment]
Oh, terribly sorry I overlooked that. In that case I will think about merging this in tomorrow, as it is a nice feature to have.
Once again - sorry I did not check this and just rambled on. 

Thank you,
Ivan

**Comment by golikov** [comment]
No worries :) It would be great if the change it made it into official branch. Would really save me a lot of trouble.

Best regards,
Nick

**Pull request merged**
