### PR TITLE
small improvements

### PR DESCRIPTION
**Pull request by duzun**
Change 1:
```js
document = window.document;
```
I have two reasons for this: 
a. preserve a local reference to real `document` in SIF (speed + safety);
b. after compilation, which renames all local variables to save space, `document` becomes a one letter variable (like `d`).

Change 2:
Less actions for same effect
```js
$div.empty().text(str) => $div.text(str) 
$div.append($($.parseHTML(str))) => .append($.parseHTML(str))
```

### CODE REVIEW

**Comment by vakata** [comment]
Thanks for sharing this. A few notes though:

1) I am not sure I get your first proposal - `_d` in my code is a local variable, so basically the same rules apply. It seems to me you are simply renaming the variable - please correct me if I am wrong. 

2) Your second proposal will not work - initially I wrote it in the same way, but that caused a lot of issues with other people returning an array of elements instead of a single element. Hence the commit: 
https://github.com/vakata/jstree/commit/2d25827b0717dbdbcf740fb6c2bda69a4a3423be

I am closing this now, as I can not merge it - it will be a regression (because of the second point). If the first point is more than a variable rename, please let me know the performance or other benefits and create a separate pull request so that I can merge.

Best regards,
Ivan

**Comment by duzun** [comment]
1) Variable `_d` is used only in next few lines. Variable `document` on the other hand is used all over the place. When I rename `_d` to `document`, I don't have to think of using the short version anywhere, and it just gets replaced automaticaly at compilation. I ran closure-compiler on both version, and notice that with `document` variable the .min file is a little bit smaller.

2) a. $.fn.text(str) replacces all child nodes, inncluding #text of matched elements, hence no need to call .empty() first.
b. $.fn.append() accepts arrays as well, hence I don't understand the need to wrap that array in a jQuery object.

Regards

**Comment by vakata** [comment]
Yes, I saw that it was used elsewhere a few minutes after posting it. Do you want to make a separate pull request for that?

As for the other fix - certain jQuery functions may work with arrays, but some do not, besides - jsTree's code depends on jQuery objects in a lot of places, and adding type checking for arrays will take a lot more lines, compared to the 3 symbols required wrapping the `$.parseHTML` call.

**Comment by duzun** [comment]
Ok, I created another PR.

Acording to [jQuery.fn.append()](http://api.jquery.com/append/) documentation, `.append()` accepts Array of elements. I'm still convinced that `.append($($.parseHTML(str)))` functionally is 100% equivalent to `.append($.parseHTML(str))`, with one extra step.

**Comment by vakata** [comment]
OK, I am terribly sorry. 

I was under the impression you modified `$.parseHTML` everywhere - like this line: https://github.com/vakata/jstree/blob/master/src/jstree.js#L1328
Now I see you only modified it in the `append` call - my mistake.

Once again - I apologize for overlooking the actual change - sorry.

**Comment by duzun** [comment]
No problem, I should have explained more precisely what are the changes.

P.S. `$div.append($($.parseHTML(str)))` is still there in `$.vakata.html.strip(str)`, but it is not that critical, unless you have thousands of calls to this method.

**Pull request closed without merging**
