### PR TITLE
Added depthFirst search to tree

### PR DESCRIPTION
**Pull request by adamkleingit**

### CODE REVIEW

**Comment by vakata** [comment]
Thank you for the pull request, but I hope you don't mind me asking what the added benefit is?

**Comment by adamkleingit** [comment]
Hi,
I needed to navigate between search results on arror-down/arrow-up keys,
so I needed them to be sorted depth first

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/> - Web and Mobile development
- hackademy.co.il <http://hackademy.co.il/angularjs/about> - AngularJS,
Ruby on Rails training
- (+972) 52 747 5633

**Comment by vakata** [comment]
I see. Once again - thanks for contributing, but I won't be merging this, it seems like a rare use case and jstree already has way too many config options. Btw - maybe the `search_leaves_only` option can be useful to you.

**Comment by adamkleingit** [comment]
No problem, I'll use my fork.
Thanks

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/> - Web and Mobile development
- hackademy.co.il <http://hackademy.co.il/angularjs/about> - AngularJS,
Ruby on Rails training
- (+972) 52 747 5633

**Pull request closed without merging**
