### PR TITLE
Select leaf only

### PR DESCRIPTION
**Pull request by rogercoder**
New 'select_leaf_only' option. This is something required by our usage of jstree. I googled and found many who wanted this, and found many different approaches to achieving this with jstree, mostly using some fancy coding. This simplifies things greatly for end user webdevs: just add 'select_leaf_only: true' to core options. Implemented for json-flat, json-nested and html data. Have visual tests in desktop-leafOnly but could not get the visual test framework to run so did not add to gruntfile.js.

### CODE REVIEW

**Comment by vakata** [comment]
Thank you for the contribution, but isn't this much cleaner and simpler:
http://jsfiddle.net/DGAF4/1302/

Let me know if this is somehow insufficient and I will reopen the pull request.

Best regards,
Ivan

**Comment by rogercoder** [comment]
With our currently in use legacy tree (which I want to use jstree to replace) there is a visual indication of which nodes are selectable and which nodes are not. In the jsfiddle you linked to the only way to tell if a node can be selected is to try to click on it. In my solution the nodes that are not selectable (ie, anything but leaf nodes) are clearly shown as disabled, leading to a less confusing user experience.

As far as simpler goes, I would have to vote for:
`select_leaf_only: true`
as being simpler (1 line) than the custom plugin you propose. At the very least, if this is the official way of supporting selecting leaf nodes only it would be great if it were documented in a FAQ entry.
Thanks for the quick reply, though, and thanks for jsTree - we love it!

**Comment by vakata** [comment]
Hi again,

Please note `conditionalselect` is not a custom plugin, it is bundled with jstree and is documented:
https://www.jstree.com/plugins/ (there is also an API entry in the respective section)

So I believe it is simpler because it is already included, but I see your point about the visual indication. I will have a look at the pull request.

Best regards,
Ivan

**Comment by vakata** [comment]
Sorry I took so long, I finally had the time to take a look again. 

Sorry, I still think the already available functionality is much simpler and more flexible to use, here is an updated demo:
http://jsfiddle.net/DGAF4/1413/
(please note `filter` is just an example - you are free to use whatever CSS you desire).

Best regards,
Ivan

**Comment by rogercoder** [comment]
I took a look at the jsfiddle ... what does the conditionalselect function do? Changing the return value to true or false has no effect.

**Comment by vakata** [comment]
If you return ```false``` and try to select any node on the tree it will not be selected (in the fiddle above). Conditionalselect does exactly that - allows you to prevent selecting nodes using a callback.

**Pull request closed without merging**
