### PR TITLE
Fixing issue with ready event being called too early when opening folders on load 

### PR DESCRIPTION
**Pull request by meh-uk**
Fixing the issue with the ready event being called too early when opening folders on load.

I have created a couple of demos - without the state plugin - on my website:
* http://matthewhutton.com/jstree-old/demo/filebrowser/
* http://matthewhutton.com/jstree/demo/filebrowser/

The "old" one is with the latest copy of the code from github, the other is with my change.

### CODE REVIEW

**Comment by vakata** [comment]
Sorry for not merging but it seems to me moving the setTimeout a few lines higher solves the problem better, as the tree won't have to be traversed every time a node is loaded, which may be slow on large trees.
Best regards,
Ivan

**Comment by meh-uk** [comment]
If you've found a better solution then I'm happy with that. I wasn't entirely convinced by my solution to be honest.

**Comment by vakata** [comment]
Test the fixed version out and let me know if you still run into any issues. Your approach was more robust, I initially tried that first but could not find a way to do this without way too complex logic and without traversing the tree. So although your approach was better and more future safe (and the way it should be done), I hope this fix will be good enough. Let me know if there is any trouble.

**Comment by meh-uk** [comment]
Just tested it - and your fix seems good enough :).

**Pull request closed without merging**
