### PR TITLE
Add: parentsload plugin to load_node() not-loaded node with all its parents

### PR DESCRIPTION
**Pull request by ashl1**

### CODE REVIEW

**Comment by vakata** [comment]
Sorry, but this already exists - `load_node` can take an array and load nodes that will appear later in the structure like: `['node1','node1.1','node1.1.1']`, and the `massload` plugin will load all those in a single request. If this commit is different in any way than the massload plugin - let me know and I will reopen.

Best regards,
Ivan

**Comment by ashl1** [comment]
This plugin differs. Let me explain.

As I understand the existed ```load_node()``` couldn't load the unknown node and all its parents in one load. Just because it doesn't know the whole parents in path. And ```massload``` only parse multiple items.

My plugin load the whole path to the requested node in one query just by giving one target node, assumes the server make the parents structure.

**Comment by vakata** [comment]
I see, sorry for not getting that - I will have a deeper look. Thank you

**Comment by ashl1** [comment]
I see two ways to approach the loading parents. Each one with some advantages and disadvantages. 

One method

Load all parents until the root  with all items on each level if unknown item will be requested.

+

* load all required info at one request
* good for small trees
* small response time, big network load

-

* may load unnecessary data
* bad for the big tree with more levels and more elements on each level 

Second method
Load the difference (only nodes from last loaded in path). This requires two queries:

1. load only the nodes (or id) on path from root to requested node, 
2. load the nodes from last loaded in that path to the requested nodes. It may use existed ```load_node()``` and ```massload``` plugin

+

* load only necessary data
* good for big trees and when a lot of work on it requires
* small network load, big response time 

-

* make two requests 
* should implement three  modes on server: load one, load many and load only path. Of course, load one might be a part of load many. 

I uses first method also on big tree and only once at session: select default value at start. I think we should implement both, but the second method requires additional changes.

**Comment by vakata** [comment]
Hi again,

After careful inspection - I will not merge this in, as that would mean I have to support this code (which is great by the way). I am just worried that adding this to the core will add a lot more config options and confusion for users that may not need this functionality.

I have however taken the liberty of adding the current copy of the plugin to `misc.js` where all 3rd party plugins live. I will make sure and recommend this to all users seeking such functionality. If there are a lot of such requests I will add this plugin to the core.

Once again - thank you :)
Best regards,
Ivan

**Pull request closed without merging**
