### PR TITLE
A plugin to optimize opening a node with large amount of children

### PR DESCRIPTION
**Pull request by xysDavid**
When opening a node which has a large amount of children(maybe more than 10000), it will slowing down the browser, because of the large amount of elements.
Using this plugin to show the first X children when opening a node. Providing a 'More...' button to show next X children in the list. It will be more efficient while opening a node with a large amount of children.

### CODE REVIEW

**Comment by vakata** [comment]
Sorry for taking so long to respond - I will review in a day or two. Thank you for your patience.

**Comment by xysDavid** [comment]
@vakata It's ok and thank you for replying

**Comment by xysDavid** [comment]
@vakata Hello~~ Is this pull request ok to merge ?

**Comment by vakata** [comment]
I finally had the time to review - sorry for the long delay in getting back to you. I am very sorry but I can not merge this into the core. 

My reasons are:
1) I was working on something similar, but with server side support - I believe adding the client side only is not a good option.
2) v.4 (almost alpha-ready) uses a virtual dom (of sorts) and only visible nodes are kept in the DOM (and reused) - **so basically rendering will not be an issue in the next version**. Adding your PR now will only mean having to support it in v.3 for a few years to come.

The good news are that the code in this PR is great, and by moving some code around you can achieve full encapsulation of this functionality - meaning that you can use your own plugin without having to modify the core, which means you can use it in your projects and still update to the latest version of jstree. 

If you allow me to I will add the plugin's code to the ```misc.js``` plugins collection.

**Pull request closed without merging**
