### PR TITLE
Fixed minor bug that results in after_close.jstree triggering before …

### PR DESCRIPTION
**Pull request by Contagious06**
Very minor, however my unit tests fail :/
Workaround: animation: false

If the tree is not in the DOM, the `after_close.jstree` event gets trigger before `close_node.jstree`.

This is due to the jquery slide up animation executing immediately:
```javascript
var $div = $("<div/>");

$div.slideUp(100, function() { console.log("slideUp") });
console.log("Something")
```

Prints:
```
slideUp
Something
```

However, adding the element to the DOM fixes this:
```javascript
var $div = $("<div/>");
$("body").append($div);

$div.slideUp(100, function() { console.log("slideUp") });
console.log("Something")
```

Prints:
```
Something
slideUp
```

### CODE REVIEW

**Comment by vakata** [comment]
Thank you for the pull request, but I would like to first confirm the issue. 

I prepared a jsfiddle - it would be great if you could show me how to reproduce the issue:
http://jsfiddle.net/DGAF4/747/

The examples there all fire the events in the correct order:
1) close a node in the DOM with animation
2) close a node in the DOM without animation
3) close a node not in the DOM with animation
4) close a node not in the DOM without animation

Maybe I misunderstood you, please help me reproduce.

Best regards,
Ivan

**Comment by Contagious06** [comment]
Thanks for that :)

Here you go:
http://jsfiddle.net/tmdrwddq/1/

From:
```javascript
$('#jstree')
```
BEFORE
AFTER
BEFORE
AFTER
BEFORE
AFTER
BEFORE
AFTER

To:
```javascript
$('<div></div>')
```
AFTER
BEFORE
BEFORE
AFTER
BEFORE
AFTER
BEFORE
AFTER


Reference to the fixed version: http://jsfiddle.net/xvq3zefn/1/
BEFORE
AFTER
BEFORE
AFTER
BEFORE
AFTER
BEFORE
AFTER

Regards,
Matt

**Comment by vakata** [comment]
Thank you. 

Btw - would you like to share your unit tests? At the time being there are absolutely no unit tests for jstree, only a scaffold. 

If your tests are compatible and you want to share them - please go ahead - it would be a great help.

**Comment by Contagious06** [comment]
No problem.

Sure, I'll have a look at adding them in :)

**Pull request merged**
