### PR TITLE
Added real checkboxes capabilities to the checkbox plugin

### PR DESCRIPTION
**Pull request by jonathonbyrdziak**
I did also add some documentation to the test directory, so that I could build out this functionality.

### CODE REVIEW

**Comment by gabhi** [comment]
why is this PR closed?

**Comment by vakata** [comment]
It is for a version that is no longer supported and this functionality exists in the current version as an optional plugin.

**Comment by gabhi** [comment]
@vakata ohh i see. Does current version support native checkbox plugin. I was not able to change the look and feel of checkboxes. Am i missing something?

**Comment by vakata** [comment]
Here is the optional plugin - copy it and include it in your page: 
https://github.com/vakata/jstree/blob/master/src/misc.js#L65

Also make sure you list the plugin name in your `plugins` config array.

**Pull request closed without merging**
