### PR TITLE
UI changes to drag-n-drop

### PR DESCRIPTION
**Pull request by lydiagu**
* If adding node after sibling node which is open, show marker below all children of sibling node, instead of directly beneath.
* Prevent node from dropping inside a node that is open - this created weird interaction where you think you are adding a node to a particular place, but it actually just drops it to dnd.inside_pos because the action is registered as an 'inside' action.
* Add CSS class to selected parent node so that users have the option of adding some style indicating where a node is being dropped.
* If adding node inside a node, don't show the marker in the middle of the node. If the node is open, instead pull the marker down to the position where the node will be inserted.

### CODE REVIEW

**Comment by lydiagu** [comment]
Hi! We are using jstree in our web application and I made some UI changes to drag and drop that were helpful for us. Just wanted to let you know about the changes and see if you were interested in using any of them, or have any feedback. Thanks!

**Comment by vakata** [comment]
Thank you for the contribution. 

Unfortunately I can not merge this right away, as I need to discuss some of the points with you (if that is OK). 
 1) I would have merged the `jstree-dnd-parent` idea right away if it was a separate pull request - great idea
 2) All the marker related changes - they need a bit of polishing - what happens if the parent node has many children and the list of those children is off-screen (when the node is opened), that would mean no indication at all is shown, which I think will be even more misleading? Any ideas on how to solve this? A downward pointing arrow at the edge of the container / window could be implemented, but that would require quite a lot of JS to achieve, which might be heavy when dragging.

Best regards,
Ivan

**Comment by lydiagu** [comment]
Thanks for the feedback! I split the jstree-dnd-parent changes into a separate PR.

Good point about the marker related changes - let me think a bit more about the behavior and get back to you with some suggestions.

**Comment by vakata** [comment]
Thank you for the separate PR. So I am closing this PR, but please - let me know as soon as you have any ideas on the marker changes.

**Pull request closed without merging**
