### PR TITLE
a11yChanges

### PR DESCRIPTION
**Pull request by dgorti**
1. aria-selected is an invalid attribute. Replaced with data-selected attribute
2. Before this change the container div is give a role  "tree'.  It had one direct descendent <UL> with a role 'group'. Hence there are no direct descendent of 'tree' with a role 'treeitem'. The change here is to move the role tree from the container div to the first UL to satisfy 1.3.1 of WCAG

### CODE REVIEW

**Comment by vakata** [comment]
I am afraid I have been down this road before - are you actually testing in Jaws and nvda using different browsers? Initially jstree was designed according to the spec and no reader/browser combination worked reliably. There have been quite a few commits recently targeting a11y by members of the community - check those out too. Anyway - let me know if you are actually fixing a problem you found with a screenreader/browser combination or just following the spec.

**Comment by dgorti** [comment]
Ivan, the aria-selected is an invalid attribute. Perhaps that spec was updated. What I am trying to do is to fix the errors generated by a11y checkers. Regarding screen readers no I have. It done that but irrespective of that these fixes are valid I would think.

**Comment by dgorti** [comment]
Let me know if you have e time for a quick call.

Thanks
Durga
Sent from mobile. Excuse any typos.

________________________________

**Comment by dgorti** [comment]
aria-selected is a valid attribute for tree items, so this PR needs rework

**Pull request closed without merging**
