### PR TITLE
Create missing .state object in node and detect invalid parent when loading alternative JSON format.

### PR DESCRIPTION
**Pull request by 0xAF**

### CODE REVIEW

**Comment by vakata** [comment]
Thanks for the contribution. A couple of questions before I merge:
1) Did the missing state object cause any issues for you? (I believe it is added later on) It is not a problem of course - just asking.
2) Do you believe catching the error and moving on is the best way to deal with the situation? I was thinking about throwing an error and stopping execution. I guess ignoring the invalid parts of the data may pile on more errors. Any thoughts on this?

**Comment by 0xAF** [comment]
1. Yes, errors in console log when the state plugin is used. And the state is not saved in the cookies.
2. I guess both ways are fine in different situations. But in my situation, when the data is coming from DB, I can have missing row (parent record), which is an error by itself, but it's easier for me if jstree ignores it and on the next saving on the tree into the DB the record will be removed.
In my case I just delete all records in the db table and insert back the records which are coming from jstree.
I will change that behavior later and I will just update the rows coming from jstree and delete the ones, which are not in jstree. But in any case, I would prefer user's work to not be interrupted by jstree and my phone ringing to provide support.
Perhaps you can make the behavior optional from the jstree.default.options.

**Comment by vakata** [comment]
Great, thanks for the input - I will merge this PR and apply some changes (options on how to handle missing parents) in a day or two.

**Comment by pnbskrishn** [comment]
[
       { "id" : "ajson1", "parent" : "#", "text" : "Simple root node" },
       { "id" : "ajson2", "parent" : "#", "text" : "Root node 2" },
       { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1" },
       { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2" },
       { "id" : "ajson5", "parent" : "ajson6", "text" : "Child 2" },
    ]
for the above json object my tree is not working , i want to show ajson5 as parent as its parent is not available in the list  can any one help me how to handle this js

**Comment by vakata** [comment]
@pnbskrishn you specified `ajson6` as parent, which does not exist - this is why its not working - provide a valid structure and it will work.

**Pull request merged**
