### PR TITLE
Integrate HTML5 drag and drop API as alternative of classical mouse t…

### PR DESCRIPTION
**Pull request by zeitiger**
…racking and allow better dnd experience outside jstree itself

### CODE REVIEW

**Comment by vakata** [comment]
The changes look great! I will merge ASAP, I am not merging right away, as I will need to immediately update a few lines, which will take some time:
 - I will see if all HTML5 events can be delegated - binding on each node individually will be very slow on large trees
 - I will remove the usage of jQuery inside redraw_node, as it will be very slow on large trees too

Thank you for the contribution and for the great work! I will get back to you in a few days when I can merge the request.

Best regards,
Ivan

**Comment by gpetrov** [comment]
@vakata Any chance to merge this soon? Seems like a very valuable addition.
Hope it will make it in the next stable version.

**Comment by vakata** [comment]
@gpetrov Sorry, I haven't found the time to properly test this out, but I hope I will in the next week.

Best regards,
Ivan

**Comment by vakata** [comment]
I just added this to the DND plugin. Thank you for the wonderful idea, unfortunately I could not merge this because of the expensive jQuery operations in redraw_node, and the events bound in the same function, but I built on this example managed to make it fully compatible with the all other options (large drag/drop target, the open_timeout, etc).

Once again - thank you.

Best regards,
Ivan

**Comment by zeitiger** [comment]
:+1: Thanks a lot

**Pull request closed without merging**
